version: '2'
services:

  influxdb:
    image: influxdb:1.8.4-alpine
    container_name: influxdb
    volumes:
      - ./influxdb:/docker-entrypoint-initdb.d
    environment:
      - INFLUXDB_DB=iqar
      - INFLUXDB_HTTP_AUTH_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=SuperSecret
      - INFLUXDB_READ_USER=grafana
      - INFLUXDB_READ_USER_PASSWORD=ReaderSecret
    ports:
      - 8086:8086

  grafana:
    image: grafana/grafana:7.4.1
    container_name: grafana
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_USERNAME=grafana
      - INFLUXDB_PASSWORD=ReaderSecret
      - INFLUXDB_DB=iqar
    ports:
      - 3000:3000
    depends_on:
      - influxdb
