services:

  timescaledb:
    image: timescale/timescaledb-ha:pg17.2-ts2.18.0-all
    container_name: timescaledb
    volumes:
      - ./timescaledb/init.sh:/docker-entrypoint-initdb.d/init.sh
      - ./timescaledb/postgres.dump:/docker-entrypoint-initdb.d/postgres.dump
    environment:
      POSTGRES_PASSWORD: "SuperSecret"
    ports:
      - 5432:5432
    healthcheck:
      test: pg_isready -U postgres -d postgres
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:8.14.0
    container_name: pgadmin
    volumes:
      - ./pgadmin/servers.json:/pgadmin4/servers.json
      - ./pgadmin/pgpass:/pgadmin4/pgpass
    environment:
      PGADMIN_DEFAULT_EMAIL: "esign@esign.com.br"
      PGADMIN_DEFAULT_PASSWORD: "S3cr3t"
      PGADMIN_CONFIG_UPGRADE_CHECK_ENABLED: "False"
    entrypoint: >
      /bin/sh -c "
      mkdir /var/lib/pgadmin/storage;
      mkdir /var/lib/pgadmin/storage/esign_esign.com.br;
      cp /pgadmin4/pgpass /var/lib/pgadmin/storage/esign_esign.com.br/;
      chmod 600 /var/lib/pgadmin/storage/esign_esign.com.br/pgpass;
      /entrypoint.sh
      "
    ports:
      - 8085:80
    healthcheck:
      test: wget http://localhost:80/misc/ping -q -O -
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      timescaledb:
        condition: service_healthy
