apiVersion: 1

datasources:
  - name: Postgres
    type: postgres
    url: $POSTGRES_URL
    user: postgres
    secureJsonData:
      password: $POSTGRES_PASSWORD
    jsonData:
      database: postgres
      sslmode: 'disable'
      maxOpenConns: 100
      maxIdleConns: 100
      maxIdleConnsAuto: true
      connMaxLifetime: 14400
      postgresVersion: 1500
      timescaledb: true
