apiVersion: 1

datasources:

  - name: influxdb1
    type: influxdb
    access: proxy
    url: $INFLUXDB_URL
    jsonData:
      dbName: $INFLUXDB_BUCKET1
      httpHeaderName1: 'Authorization'
    secureJsonData:
      httpHeaderValue1: 'Token $INFLUXDB_TOKEN'

  - name: influxdb2
    type: influxdb
    access: proxy
    url: $INFLUXDB_URL
    jsonData:
      dbName: $INFLUXDB_BUCKET2
      httpHeaderName1: 'Authorization'
    secureJsonData:
      httpHeaderValue1: 'Token $INFLUXDB_TOKEN'
