name: Build and Push Docker Image to Docker Hub

on: [push]

jobs:
  push_to_registry:
    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          push: true
          tags: esignbr/qualidade-ar-smac:latest
