name: Build and Push Docker Image to Docker Hub

on: [push]

jobs:
  push_to_registry:
    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Log in Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64
      - name: Build and Push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: esignbr/qualidade-ar-smac:latest
