name: Java CI/CD with Maven

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK 21.0.2
        uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: 21.0.2
          cache: 'maven'
      - name: Build with Maven
        run: mvn verify sonar:sonar -Dsonar.token=${{ secrets.SONAR_TOKEN }}
      - name: Deploy to Maven Repository
        run: mvn -Dmaven.test.skip=true deploy -s settings.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Package the function
        run: mvn clean package
      - name: Deploy to Azure
        run: mvn azure-functions:deploy

  python:
    needs: build
    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
            python-version: '3.x'
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
      - name: Test with pytest
        run: |
            pytest airflow/apiclient-test.py
