name: Java CI/CD with Maven

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK 21.0.2
        uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: 21.0.2
          cache: 'maven'
      - name: Build with Maven
        run: mvn verify sonar:sonar -Dsonar.token=${{ secrets.SONAR_TOKEN }}
      - name: Deploy to Maven Repository
        run: mvn -Dmaven.test.skip=true deploy -s settings.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Prepare JAR file to upload
        run: |
          mkdir ./jar-upload
          cp ./target/qualidadearsmac-0.0.1-SNAPSHOT.jar ./jar-upload
      - name: Upload JAR file
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.ESIGN_HOST }}
          username: ${{ secrets.ESIGN_USERNAME }}
          password: ${{ secrets.ESIGN_PASSWORD }}
          local-dir: ./jar-upload/
          server-dir: ~/appservers/standalone/
      - name: Stop remote Sprint Boot
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.ESIGN_HOST }}
          username: ${{ secrets.ESIGN_USERNAME }}
          password: ${{ secrets.ESIGN_PASSWORD }}
          script: appservers/tmp/qualidadearsmac-0.0.1-SNAPSHOT.sh stop
      - name: Start remote Sprint Boot
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.ESIGN_HOST }}
          username: ${{ secrets.ESIGN_USERNAME }}
          password: ${{ secrets.ESIGN_PASSWORD }}
          script: appservers/tmp/qualidadearsmac-0.0.1-SNAPSHOT.sh start
